name: 'CI/CD Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq libimage-exiftool-perl shellcheck

      - name: Run linter
        run: |
          shellcheck qs qs_test install.sh

      - name: Run tests
        run: |
          ./qs_test

  macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          brew install jq exiftool curl

      - name: Run tests
        run: |
          ./qs_test
